# -*- coding: utf-8 -*-
"""
Created on 2022-05-18 00:51:26
---------
@summary:
---------
@author: ASUS
"""

from feapder import Item


class IpPoolItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i ip_pool 1
    """

    __table_name__ = "ip_pool"

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.ip = kwargs.get('ip')
        self.port = kwargs.get('port')
        self.anonymity = kwargs.get('anonymity')
        self.type = kwargs.get('type')
        self.location = kwargs.get('location')
        self.socket = kwargs.get('socket')
        self.data = kwargs.get('data')
